# Generated by Django 5.0.1 on 2024-03-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='supportingimage',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='supportingimage2',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='supportingimage3',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
